### ISSUE TITLE
discord Id search leads to second search menu on andriod

### ISSUE THREAD

**Issue by aswhale** [CryptoCoderz/uunigate-site#3]
On andriod, when searching by discord ID, when you click on a search results, it takes you to a second d search menu.  This is different than the first menu

![Screenshot_20230506_154332_Firefox](https://user-images.githubusercontent.com/114945271/236643776-fdb6a378-7d0c-441f-b347-555b9ec49409.jpg)

![Screenshot_20230506_154340_Firefox](https://user-images.githubusercontent.com/114945271/236643779-5ddfbb50-16f9-4414-8295-c18c11dd7598.jpg)

**Comment by CryptoCoderz** [comment]
This is normal operation, when you click the Discord ID you searched you are now viewing all NFTs that are assigned to that ID and are able to search through them.
